name: newscleanapp
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dio: ^5.3.0
  equatable: ^2.0.5
  floor: ^1.4.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.19.0
  get_it: ^7.6.0
  intl: ^0.18.1
  ionicons: ^0.2.2
  json_serializable: ^6.7.1
  retrofit: ^4.0.1
  sqflite: ^2.3.0
dev_dependencies:
  build_runner: ^2.4.6
  floor_generator: ^1.4.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  retrofit_generator: ^7.0.8

flutter:
  uses-material-design: true
  assets:
    - assets/placeholder.jpg
